executor: local
cores: 32
jobs: 32
use-conda: true
rerun-incomplete: true
keep-going: true
latency-wait: 60
printshellcmds: true
show-failed-logs: true
software-deployment-method:
  - conda
default-resources:
  - mem_mb=4000
  - disk_mb=10000
